# Generated by Django 6.0.1 on 2026-01-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
